name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.3.0"
pack-format = "packwiz:1.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5e9794061fc8c8ddfa3aca9a0a1dc06c6fab3d98691202b69521d895f6ead56"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
