name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.3.0"
pack-format = "packwiz:1.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b8ddd9cb019d07fe609e505d8af5082ea92f7ee6ad6063e1cf367974eeabf1"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
