name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.3.0"
pack-format = "packwiz:1.3.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cccf707d1486361adf17c33cb294e9e77b23562dfb327d59eca6c5d932bae5d0"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
