name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.2.0"
pack-format = "packwiz:1.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38fb7adf8b319551b1a05cfb5db7b18717b400d85872025f251ad678f071e3f7"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
