name = "Minecraft Warfare III"
author = "HiWhatName,RGB__Toaster,JusPLP,PennyManager?"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb0aaf89a77165bee93f44b9e16cee043187139c106042b06b39b164bc804626"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
