name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.2.1"
pack-format = "packwiz:1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7582eb5d56481449725c947e1d33329767c230cd76453e53c9c90c30ef2831f9"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
