name = "Minecraft Warfare III"
author = "HiWhatName"
version = "1.2.0"
pack-format = "packwiz:1.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9935d7ed71edbf7ae3209c3ef0acb7361200d633191a708f34fc46c14f5e2d2d"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
