
#Config File for Trajan's Tank Mod
["Panzer 2 Stats"]
	"Panzer 2 Health (0-250)" = 800.0
	"Panzer 2 Speed" = 0.21
	"Panzer 2 Shot Cooldown (1 = 1/20 second)" = 50
	"Panzer 2 Healing Amount (on right click)" = 10.0
	"Panzer 2 Max Fuel (seconds)" = 760.0

["Tiger Stats"]
	"Tiger Health (0-250)" = 1100.0
	"Tiger Speed" = 0.16
	"Tiger Shoot Cooldown (1 = 1/20 second" = 50
	"Tiger Healing Amount (on right click)" = 10.0
	"Tiger Max Fuel (seconds)" = 760.0

["T-34 Stats"]
	"T-34 Health (0-250)" = 950.0
	"T-34 Speed" = 0.18
	"T-34 Shoot Cooldown (1 = 1/20 second" = 35
	"T-34 Healing Amount (on right click)" = 10.0
	"T-34 Max Fuel (seconds)" = 760.0

["Cruiser MK1 Stats"]
	"Cruiser MK1 Health (0-250)" = 800.0
	"Cruiser MK1 Speed" = 0.21
	"Cruiser MK1 Shoot Cooldown (1 = 1/20 second" = 32
	"Cruiser MK1 Healing Amount (on right click)" = 10.0
	"Cruiser MK1 Max Fuel (seconds)" = 760.0

["M4 Sherman Stats"]
	"M4 Sherman Health (0-250)" = 850.0
	"M4 Sherman Speed" = 0.18
	"M4 Sherman Shoot Cooldown (1 = 1/20 second" = 40
	"M4 Sherman Healing Amount (on right click)" = 10.0
	"M4 Sherman Max Fuel (seconds)" = 760.0

["Archer Stats"]
	"Archer Health (0-250)" = 900.0
	"Archer Speed" = 0.18
	"Archer Shoot Cooldown (1 = 1/20 second" = 40
	"Archer Healing Amount (on right click)" = 10.0
	"Archer Max Fuel (seconds)" = 760.0

["KV-2 Stats"]
	"KV-2 Health (0-250)" = 1125.0
	"KV-2 Speed" = 0.16
	"KV-2 Shoot Cooldown (1 = 1/20 second" = 50
	"KV-2 Healing Amount (on right click)" = 10.0
	"KV-2 Max Fuel (seconds)" = 760.0

["Jagdpanther Stats"]
	"Jagdpanther Health (0-250)" = 1100.0
	"Jagdpanther Speed" = 0.16
	"Jagdpanther Shoot Cooldown (1 = 1/20 second" = 50
	"Jagdpanther Healing Amount (on right click)" = 10.0
	"Jagdpanther Max Fuel (seconds)" = 760.0

["Pak-40 Stats"]
	"Pak-40 Health" = 105.0
	"Pak-40 Shot Cooldown (1 = 1/20 second)" = 35

["Qf-6 Stats"]
	"QF-6 Health" = 105.0
	"QF-6 Shot Cooldown (1 = 1/20 second)" = 35

